FROM nvcr.io/nvidia/pytorch:21.07-py3

COPY requirements.txt opt/app/requirements.txt
WORKDIR opt/app

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install -r requirements.txt