FROM nvcr.io/nvidia/pytorch:21.07-py3

COPY requirements.txt opt/app/requirements.txt
WORKDIR opt/app

RUN apt-get update -y
RUN apt-get install -y libpq-dev python3-dev
 
RUN pip install -r requirements.txt